---
  - name: Verify
    hosts: all
    become: true
    tasks:
      - name: Check that ~/.custom-bashrc/bashrc does not exist
        stat:
          path: ~/.custom-bashrc/bashrc
        register: verify_custom_bashrc
        failed_when: verify_custom_bashrc.stat.exists

      - name: Check that global bashrc exists
        stat:
          path: /opt/bashrc/bashrc
        register: verify_global_bashrc
        failed_when: not verify_global_bashrc.stat.exists

      - name: Check that custom bashrc is not present in ~/.bashrc
        blockinfile:
          path: ~/.bashrc
          block: |
            if [ -f ~/.custom-bashrc/bashrc ]; then
              . ~/.custom-bashrc/bashrc
            fi
        check_mode: yes
        register: verify_current_user_bashrc
        failed_when: not verify_current_user_bashrc.changed

      - name: Check that /opt/bashrc is present in Users .bashrc
        blockinfile:
          path: /home/{{ item }}/.bashrc
          block: |
            if [ -f /opt/bashrc/bashrc ]; then
            . /opt/bashrc/bashrc
            fi
        check_mode: yes
        with_items:
          - vagrant
          - gepardec
        register: verify_users_bashrc
        failed_when: verify_users_bashrc.changed

      - name: Check that /etc/bashrc does not contain /opt/bashrc/bashrc
        blockinfile:
          path: /etc/bashrc
          block: |
            if [ -f /opt/bashrc/bashrc ]; then
            . /opt/bashrc/bashrc
            fi
        check_mode: yes
        register: verify_etc_bashrc
        failed_when: not verify_etc_bashrc.changed
...